<a href="https://colab.research.google.com/github/Paxlawa/Labu/blob/main/%D0%9B%D0%A01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

print("Версія NumPy:", np.__version__)

Версія NumPy: 2.1.3


In [2]:
arr = np.array([2, 4, 6, 8, 10])

print("Масив:", arr)
print("Тип:", type(arr))

Масив: [ 2  4  6  8 10]
Тип: <class 'numpy.ndarray'>


In [3]:
zeros = np.zeros(10)
ones = np.ones(8)
sevens = np.full(6, 7)

print("10 нулів:", zeros)
print("8 одиниць:", ones)
print("6 сімок:", sevens)

10 нулів: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8 одиниць: [1. 1. 1. 1. 1. 1. 1. 1.]
6 сімок: [7 7 7 7 7 7]


In [4]:
numbers = np.arange(1, 21)
even_numbers = np.arange(2, 21, 2)

print("Числа від 1 до 20:", numbers)
print("Парні числа:", even_numbers)

Числа від 1 до 20: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Парні числа: [ 2  4  6  8 10 12 14 16 18 20]


In [5]:
numbers = np.linspace(0, 1, 11)

print("Масив:", numbers)

Масив: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [7]:
numbers = np.arange(1, 13)
matrix = numbers.reshape(3, 4)

print("Матриця:")
print(matrix)

Матриця:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [8]:
print("Кількість вимірів:", matrix.ndim)
print("Форма:", matrix.shape)
print("Кількість елементів:", matrix.size)
print("Тип даних:", matrix.dtype)

Кількість вимірів: 2
Форма: (3, 4)
Кількість елементів: 12
Тип даних: int64


In [9]:
arr = np.array([1.2, 3.5, 5.7, 7.9])
integer_arr = arr.astype(int)

print("Початковий масив:", arr)
print("Масив цілих чисел:", integer_arr)

Початковий масив: [1.2 3.5 5.7 7.9]
Масив цілих чисел: [1 3 5 7]


In [10]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

print("Перший елемент:", arr[0])
print("Останній елемент:", arr[-1])
print("Елементи з індексами 2-5:", arr[2:6])
print("Кожен другий елемент:", arr[::2])

Перший елемент: 10
Останній елемент: 80
Елементи з індексами 2-5: [30 40 50 60]
Кожен другий елемент: [10 30 50 70]


In [12]:
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Матриця:")
print(matrix)

print("Елемент 7:", matrix[1, 2])
print("Другий рядок:", matrix[1])
print("Третій стовпець:", matrix[:, 2])
print("Підматриця:")
print(matrix[1:3, 0:2])

Матриця:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Елемент 7: 7
Другий рядок: [5 6 7 8]
Третій стовпець: [ 3  7 11]
Підматриця:
[[ 5  6]
 [ 9 10]]


In [11]:
arr = np.arange(1, 16)

arr[5:10] = 0

print("Результат:", arr)

Результат: [ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


In [13]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Додавання:", a + b)
print("Віднімання:", a - b)
print("Множення:", a * b)
print("Ділення:", a / b)

Додавання: [11 22 33 44 55]
Віднімання: [ -9 -18 -27 -36 -45]
Множення: [ 10  40  90 160 250]
Ділення: [0.1 0.1 0.1 0.1 0.1]


In [14]:
arr = np.array([4, 8, 15, 16, 23, 42])

print("Сума:", np.sum(arr))
print("Середнє:", np.mean(arr))
print("Мінімум:", np.min(arr))
print("Максимум:", np.max(arr))
print("Медіана:", np.median(arr))
print("Стандартне відхилення:", np.std(arr))

Сума: 108
Середнє: 18.0
Мінімум: 4
Максимум: 42
Медіана: 15.5
Стандартне відхилення: 12.315302134607444


In [15]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print("Матриця:")
print(matrix)

print("Загальна сума:", np.sum(matrix))
print("Сума стовпців:", np.sum(matrix, axis=0))
print("Сума рядків:", np.sum(matrix, axis=1))
print("Середнє стовпців:", np.mean(matrix, axis=0))

Матриця:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Загальна сума: 45
Сума стовпців: [12 15 18]
Сума рядків: [ 6 15 24]
Середнє стовпців: [4. 5. 6.]


In [16]:
arr = np.arange(1, 11)

print("Числа:", arr)
print("Квадрат:", np.square(arr))
print("Квадратний корінь:", np.sqrt(arr))
print("Натуральний логарифм:", np.log(arr))

Числа: [ 1  2  3  4  5  6  7  8  9 10]
Квадрат: [  1   4   9  16  25  36  49  64  81 100]
Квадратний корінь: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Натуральний логарифм: [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


In [19]:
arr = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print("Більше 15:", arr[arr > 15])
print("Парні числа:", arr[arr % 2 == 0])
print("Від 10 до 30:", arr[(arr >= 10) & (arr <= 30)])

Більше 15: [18 21 25 30 34]
Парні числа: [12 18 30 34]
Від 10 до 30: [12 18 21 25 30]


In [20]:
arr = np.array([-5, 3, -2, 8, -1, 10, 0])

arr[arr < 0] = 0

print("Результат:", arr)

Результат: [ 0  3  0  8  0 10  0]


In [21]:
np.random.seed(42)

arr = np.random.randint(0, 101, 20)

print("Масив:", arr)
print("Кількість > 50:", np.sum(arr > 50))
print("Кількість <= 50:", np.sum(arr <= 50))

Масив: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Кількість > 50: 12
Кількість <= 50: 8


In [22]:
arr = np.arange(1, 25)

matrix_4x6 = arr.reshape(4, 6)
matrix_6x4 = arr.reshape(6, 4)
matrix_2x3x4 = arr.reshape(2, 3, 4)

print("Форма 4x6:", matrix_4x6.shape)
print(matrix_4x6)

print("\nФорма 6x4:", matrix_6x4.shape)
print(matrix_6x4)

print("\nФорма 2x3x4:", matrix_2x3x4.shape)
print(matrix_2x3x4)

Форма 4x6: (4, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Форма 6x4: (6, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Форма 2x3x4: (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [23]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

vertical = np.concatenate((A, B), axis=0)
horizontal = np.concatenate((A, B), axis=1)

print("Вертикальне об'єднання:")
print(vertical)

print("\nГоризонтальне об'єднання:")
print(horizontal)

Вертикальне об'єднання:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Горизонтальне об'єднання:
[[1 2 5 6]
 [3 4 7 8]]


In [24]:
matrix = np.arange(1, 13).reshape(3, 4)

flatten_array = matrix.flatten()
ravel_array = matrix.ravel()

print("Початкова матриця:")
print(matrix)

print("\nFlatten:")
print(flatten_array)

print("\nRavel:")
print(ravel_array)

print("\nFlatten і Ravel однакові:", np.array_equal(flatten_array, ravel_array))

Початкова матриця:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Flatten:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Ravel:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Flatten і Ravel однакові: True


In [25]:
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

vector_sum = a + b
vector_diff = a - b
a_mult_3 = a * 3
b_mult_3 = b * 3

print("Завдання 21:")
print("Сума векторів:", vector_sum)
print("Різниця векторів:", vector_diff)
print("Вектор a * 3:", a_mult_3)
print("Вектор b * 3:", b_mult_3)
print("-" * 40)

Завдання 21:
Сума векторів: [ 3  7 11]
Різниця векторів: [1 1 1]
Вектор a * 3: [ 6 12 18]
Вектор b * 3: [ 3  9 15]
----------------------------------------


In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

dot_1 = np.dot(a, b)
dot_2 = a @ b

print("Завдання 22:")
print("Скалярний добуток (np.dot):", dot_1)
print("Скалярний добуток (@):", dot_2)
print("-" * 40)

Завдання 22:
Скалярний добуток (np.dot): 32
Скалярний добуток (@): 32
----------------------------------------


In [27]:
v = np.array([3, 4])

norm = np.linalg.norm(v)

v_normalized = v / norm

print("Завдання 23:")
print("Евклідова норма:", norm)
print("Нормалізований вектор:", v_normalized)
print("-" * 40)

Завдання 23:
Евклідова норма: 5.0
Нормалізований вектор: [0.6 0.8]
----------------------------------------


In [28]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

cross_product = np.cross(a, b)

print("Завдання 24:")
print("Векторний добуток:", cross_product)
print("-" * 40)

Завдання 24:
Векторний добуток: [0 0 1]
----------------------------------------


In [29]:
a = np.array([1, 2])
b = np.array([2, 1])

cos_angle = np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

angle_rad = np.arccos(cos_angle)
angle_deg = np.degrees(angle_rad)

print("Завдання 25:")
print("Косинус кута:", cos_angle)
print("Кут у градусах:", angle_deg)
print("-" * 40)

Завдання 25:
Косинус кута: 0.7999999999999998
Кут у градусах: 36.86989764584404
----------------------------------------


In [30]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

A_T_1 = A.T
A_T_2 = np.transpose(A)

print("Завдання 26:")
print("Транспонована (.T):\n", A_T_1)
print("Транспонована (np.transpose):\n", A_T_2)
print("-" * 40)

Завдання 26:
Транспонована (.T):
 [[1 4]
 [2 5]
 [3 6]]
Транспонована (np.transpose):
 [[1 4]
 [2 5]
 [3 6]]
----------------------------------------


In [31]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[2, 0],
              [1, 2]])

elem_mult = A * B
matmul = A @ B

print("Завдання 27:")
print("Поелементний добуток (A * B):\n", elem_mult)
print("Матричний добуток (A @ B):\n", matmul)

print("-" * 40)

Завдання 27:
Поелементний добуток (A * B):
 [[2 0]
 [3 8]]
Матричний добуток (A @ B):
 [[ 4  4]
 [10  8]]
----------------------------------------


In [32]:
A = np.array([[4, 7],
              [2, 6]])

det = np.linalg.det(A)
A_inv = np.linalg.inv(A)


check = A @ A_inv

print("Завдання 28:")
print("Визначник:", det)
print("Обернена матриця:\n", A_inv)
print("Перевірка (A @ A_inv):\n", check)
print("-" * 40)

Завдання 28:
Визначник: 10.000000000000002
Обернена матриця:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Перевірка (A @ A_inv):
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
----------------------------------------


In [33]:
A = np.array([[2, 1],
              [1, 3]])

b = np.array([5, 6])

x = np.linalg.solve(A, b)

print("Завдання 29:")
print("Розв'язок системи (x, y):", x)
print("-" * 40)

Завдання 29:
Розв'язок системи (x, y): [1.8 1.4]
----------------------------------------


In [34]:
E = np.eye(4)
M = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

product = M @ E
is_equal = np.array_equal(product, M)

print("Завдання 30:")
print("Одинична матриця 4х4:\n", E)
print("Результат множення M @ E дорівнює M:", is_equal)
print("-" * 40)

Завдання 30:
Одинична матриця 4х4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Результат множення M @ E дорівнює M: True
----------------------------------------


In [35]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

res_31 = A + 10

print("Завдання 31:\n", res_31)
print("-" * 40)

Завдання 31:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
----------------------------------------


In [36]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

v = np.array([10, 20, 30])

res_32 = A + v

print("Завдання 32:\n", res_32)
print("-" * 40)

Завдання 32:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
----------------------------------------


In [37]:
A = np.array([[10, 20, 30],
              [20, 30, 40],
              [30, 40, 50]])

mu = np.mean(A, axis=0)
sigma = np.std(A, axis=0)

z = (A - mu) / sigma

print("Завдання 33 (Нормалізована матриця):\n", z)
print("-" * 40)

Завдання 33 (Нормалізована матриця):
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]
----------------------------------------


In [38]:
np.random.seed(42)

rand_integers = np.random.randint(1, 101, size=10)
rand_matrix = np.random.rand(3, 3)
norm_dist = np.random.normal(size=1000)

mean_norm = np.mean(norm_dist)
std_norm = np.std(norm_dist)

print("Завдання 34:")
print("10 випадкових цілих чисел:", rand_integers)
print("Матриця 3х3:\n", rand_matrix)
print("Нормальний розподіл (середнє):", mean_norm)
print("Нормальний розподіл (ст. відхилення):", std_norm)
print("-" * 40)

Завдання 34:
10 випадкових цілих чисел: [52 93 15 72 61 21 83 87 75 75]
Матриця 3х3:
 [[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
Нормальний розподіл (середнє): 0.02216865975826456
Нормальний розподіл (ст. відхилення): 0.9792284455184356
----------------------------------------


In [39]:
np.random.seed(42)
grades = np.random.randint(0, 101, size=30)

avg_grade = np.mean(grades)
median_grade = np.median(grades)
max_grade = np.max(grades)
min_grade = np.min(grades)

count_60_plus = np.sum(grades >= 60)
pct_90_plus = (np.sum(grades >= 90) / len(grades)) * 100

print("Завдання 35:")
print("Оцінки:", grades)
print("Середня оцінка:", avg_grade)
print("Медіана:", median_grade)
print("Найвища оцінка:", max_grade)
print("Найнижча оцінка:", min_grade)
print("Кількість студентів (>= 60):", count_60_plus)
print("Відсоток студентів (>= 90):", pct_90_plus, "%")
print("-" * 40)

Завдання 35:
Оцінки: [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37  1 63 59 20
 32 75 57 21 88 48]
Середня оцінка: 50.86666666666667
Медіана: 54.5
Найвища оцінка: 99
Найнижча оцінка: 1
Кількість студентів (>= 60): 13
Відсоток студентів (>= 90): 6.666666666666667 %
----------------------------------------


In [40]:
sales = np.array([[120, 150, 170, 160],
                  [80,  90,  100, 110],
                  [200, 180, 210, 230]])

total_per_product = np.sum(sales, axis=1)
total_per_month = np.sum(sales, axis=0)

best_product_idx = np.argmax(total_per_product) + 1
best_month_idx = np.argmax(total_per_month) + 1

avg_per_product = np.mean(sales, axis=1)

print("Завдання 36:")
print("Загальний обсяг продажів кожного товару:", total_per_product)
print("Загальний обсяг продажів у кожному місяці:", total_per_month)
print(f"Товар із найбільшими продажами: Товар №{best_product_idx}")
print(f"Місяць із найбільшим обсягом продажів: Місяць №{best_month_idx}")
print("Середній обсяг продажів кожного товару:", avg_per_product)
print("-" * 40)

Завдання 36:
Загальний обсяг продажів кожного товару: [600 380 820]
Загальний обсяг продажів у кожному місяці: [400 420 480 500]
Товар із найбільшими продажами: Товар №3
Місяць із найбільшим обсягом продажів: Місяць №4
Середній обсяг продажів кожного товару: [150.  95. 205.]
----------------------------------------


In [41]:
np.random.seed(42)
M = np.random.randint(1, 21, size=(5, 5))

main_diag_sum = np.trace(M)
side_diag_sum = np.trace(np.fliplr(M))

max_per_row = np.max(M, axis=1)
min_per_col = np.min(M, axis=0)

M_modified = M.copy()
M_modified[M_modified < np.mean(M)] = 0

print("Завдання 37:")
print("Початкова матриця:\n", M)
print("Сума головної діагоналі:", main_diag_sum)
print("Сума побічної діагоналі:", side_diag_sum)
print("Максимуми в кожному рядку:", max_per_row)
print("Мінімуми в кожному стовпці:", min_per_col)
print("Матриця після заміни елементів (< mean) на 0:\n", M_modified)
print("-" * 40)

Завдання 37:
Початкова матриця:
 [[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]
 [10 16 15 15 19]]
Сума головної діагоналі: 59
Сума побічної діагоналі: 32
Максимуми в кожному рядку: [20 19 12 17 19]
Мінімуми в кожному стовпці: [ 2  1  2 11  4]
Матриця після заміни елементів (< mean) на 0:
 [[ 0 20 15 11  0]
 [ 0 19 11 11  0]
 [ 0  0  0 12  0]
 [ 0  0 12 12 17]
 [ 0 16 15 15 19]]
----------------------------------------


In [44]:
X = np.array([[2, 4, 6],
              [1, 3, 5],
              [5, 7, 9]])

dist_1_2 = np.linalg.norm(X[0] - X[1])
dist_1_3 = np.linalg.norm(X[0] - X[2])
dist_2_3 = np.linalg.norm(X[1] - X[2])

print("Завдання 38:")
print("Відстань між 1 та 2 рядками:", dist_1_2)
print("Відстань між 1 та 3 рядками:", dist_1_3)
print("Відстань між 2 та 3 рядками:", dist_2_3)
print("-" * 40)

Завдання 38:
Відстань між 1 та 2 рядками: 1.7320508075688772
Відстань між 1 та 3 рядками: 5.196152422706632
Відстань між 2 та 3 рядками: 6.928203230275509
----------------------------------------


In [42]:
np.random.seed(42)
A = np.random.randint(1, 10, size=(4, 4))

row_norms = np.linalg.norm(A, axis=1, keepdims=True)

A_normalized = A / row_norms

print("Завдання 39:")
print("Початкова матриця:\n", A)
print("Нормалізована матриця (кожен рядок одиничної довжини):\n", A_normalized)
print("-" * 40)

Завдання 39:
Початкова матриця:
 [[7 4 8 5]
 [7 3 7 8]
 [5 4 8 8]
 [3 6 5 2]]
Нормалізована матриця (кожен рядок одиничної довжини):
 [[0.56407607 0.32232919 0.64465837 0.40291148]
 [0.53530338 0.22941573 0.53530338 0.61177529]
 [0.38461538 0.30769231 0.61538462 0.61538462]
 [0.34874292 0.69748583 0.58123819 0.23249528]]
----------------------------------------


In [43]:
A = np.array([[1, 2, 1],
              [2, 1, -1],
              [3, -1, 2]])

b = np.array([9, 8, 3])

x = np.linalg.solve(A, b)
b_check = A @ x

print("Завдання 40:")
print("Знайдений розв'язок (x, y, z):", x)
print("Результат A @ x:", b_check)
print("Чи збігається A @ x з b?:", np.allclose(b_check, b))

Завдання 40:
Знайдений розв'язок (x, y, z): [ 2.22222222  3.44444444 -0.11111111]
Результат A @ x: [9. 8. 3.]
Чи збігається A @ x з b?: True
