Був присутній на парі

In [ ]:
import numpy as np
det = np.linalg.det(matrix)
det
np.float64(-34.00000000000001)

np.__version__


'2.0.2'

In [ ]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[5, 4, 5],
       [3, 4, 2],
       [5, 2, 2]])

In [ ]:
det = np.linalg.det(matrix)
det

np.float64(-34.00000000000001)

In [ ]:
product = np.prod(matrix)
product

np.int64(48000)

In [ ]:
det = np.linalg.det(matrix)
det


np.float64(-34.00000000000001)

In [ ]:
product = np.prod(matrix)
product


np.int64(48000)

In [ ]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1 * prod_2 * prod_3


np.int64(48000)

In [ ]:
np.sum(matrix)


np.int64(32)

In [ ]:
np.max(matrix)


np.int64(5)

In [ ]:
np.min(matrix)


np.int64(2)

In [ ]:
np.mean(matrix)


np.float64(3.5555555555555554)

In [ ]:
sqrt_matrix = np.sqrt(matrix)

print("Матриця квадратних коренів:")
print(sqrt_matrix)


Матриця квадратних коренів:
[[2.23606798 2.         2.23606798]
 [1.73205081 2.         1.41421356]
 [2.23606798 1.41421356 1.41421356]]


In [ ]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)

print("Сума елементів кожного рядка:")
print(row_sums)


Сума елементів кожного рядка:
[[14]
 [ 9]
 [ 9]]


In [ ]:
matrix.sum(axis=1).reshape(-1, 1)


array([[14],
       [ 9],
       [ 9]])

In [ ]:
x = np.matrix([[1, 2], [4, 3]])
x


matrix([[1, 2],
        [4, 3]])

In [ ]:
vector = np.random.randint(0, 10, size=25)
vector

array([6, 9, 1, 8, 6, 2, 3, 2, 2, 2, 3, 3, 4, 9, 7, 8, 5, 5, 3, 0, 8, 6,
       6, 0, 0])

In [ ]:
sorted_vector = np.sort(vector)[::-1]
sorted_vector

array([9, 9, 8, 8, 8, 7, 6, 6, 6, 6, 5, 5, 4, 3, 3, 3, 3, 2, 2, 2, 2, 1,
       0, 0, 0])

In [ ]:
from scipy import stats
mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean(vector)

In [ ]:
from scipy import stats
import numpy as np
mode = stats.mode(vector)
median = np.median(vector)
mean = np.mean(vector)
max_value = np.max(vector)
min_value = np.min(vector)


In [ ]:
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)


Матриця 1:
[[ 7  1  8  2]
 [ 4  2  9  5]
 [ 3  7  6  4]
 [ 8  4 10  6]]

Матриця 2:
[[ 7  7  9  1]
 [ 2  9  8  7]
 [10  7  8  4]
 [ 5  3  3  3]]


In [ ]:
matrix_sum = matrix1 + matrix2
matrix_diff = matrix1 - matrix2
matrix_product = matrix1 * matrix2
matrix_division = np.divide(matrix1, matrix2, where=(matrix2 != 0))
print("\nСума матриць:")
print(matrix_sum)
print("\nРізниця матриць:")
print(matrix_diff)
print("\nПоелементний добуток матриць:")
print(matrix_product)



Сума матриць:
[[14  8 17  3]
 [ 6 11 17 12]
 [13 14 14  8]
 [13  7 13  9]]

Різниця матриць:
[[ 0 -6 -1  1]
 [ 2 -7  1 -2]
 [-7  0 -2  0]
 [ 3  1  7  3]]

Поелементний добуток матриць:
[[49  7 72  2]
 [ 8 18 72 35]
 [30 49 48 16]
 [40 12 30 18]]


In [ ]:
x = np.arange(9.)
x




array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
x1 = x.reshape((3, 3))
x1


array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [ ]:

x2 = np.arange(3.)
x2



array([0., 1., 2.])

In [ ]:

np.multiply(x1, x2)


array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [ ]:
x1 = np.arange(6)
x1


array([0, 1, 2, 3, 4, 5])

In [ ]:
np.power(x1, 3)


array([  0,   1,   8,  27,  64, 125])

In [ ]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2


array([ 0,  1,  8, 27, 16,  5])

In [ ]:
x2 = np.array([1, 2, 3, 3, 2, 1])
x2


array([1, 2, 3, 3, 2, 1])

In [ ]:
x1 = np.arange(6)
x1


array([0, 1, 2, 3, 4, 5])

In [ ]:
x1 ** x2


array([ 0,  1,  8, 27, 16,  5])

In [ ]:
np.power(x1, x2)


array([ 0,  1,  8, 27, 16,  5])